# Taken from hatch :)

line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
"E302",
"E501",
"E251",
  ]

[lint.isort]
known-first-party = ["git_pyinit"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
