
name: Linting Stage

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.8']
      steps:
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort pyflakes

      - name: Analyzing code with isort
        run: |
          isort $(git ls-files '*.py') --check-only

      - name: Analyzing code with pyflakes
        run: |
          pyflakes $(git ls-files '*.py') 
